# Generated by Django 2.2.7 on 2021-03-19 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_auto_20210319_2132'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordermodel',
            old_name='emails',
            new_name='email',
        ),
    ]
